# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d3845dccc95b8bf63a55f8050b7299a03eaf9495cefc11af461b677c415d6e3731950f6eb1b837e200f31ad7f9ce4ad7cdd73c52bc2f2b07655fba793fac01f

test:
  secret_key_base: 1814c82f0eddbfbcb76f17e1f8995caac7e125d06acebb7aed1345cf0ab55bcd4c1b0c965bb4a808f63297caaa13fdf6ee9996510dce3a7053fc66a2926b01ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
